Added avatar component
js-tasks-ru/htmlcss-20210916_irina-nic-yu pull request #13
Opened 2021-10-04 09:45 UTC by irinanic88

2021-10-04 09:45 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-10-04 16:37 UTC, GSemikozov requested changes

2021-10-04 16:37 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +    width: 100%;
вот для аватара как раз тот случай когда мы хотим чтобы он всегда был одного размера , поэтому - надо. задать фиксированные размеры как в макете

2021-10-04 18:25 UTC, irinanic88 commented on 06-lection4/01-avatar/avatar.css
> +    width: 100%;
Понятно. Добавила

2021-10-05 14:44 UTC, GSemikozov approved these changes

2021-10-05 14:44 UTC, merged