added text-input
js-tasks-ru/htmlcss-20210916_irina-nic-yu pull request #20
Opened 2021-10-08 09:02 UTC by irinanic88

2021-10-08 09:03 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-10-09 09:20 UTC, GSemikozov requested changes

2021-10-09 09:20 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +            <input type="text" class="text-input__container" disabled
disabled наверно будет лишним (не сможем взаимодействовать). Или - это просто чтобы отобразить это специфическое состояние?

2021-10-09 09:20 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.text-input__container {
__container -> __field

2021-10-09 09:20 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.text-input__container_success ~ .text-input__success-icon {
удобнее будет добавить модификаторы не на __container, а на весь блок - .text-input. Поскольку может потребоваться показывать еще какое-то сообщение об ошибке под инпутом (как в бутстрапе). Но если решим оставить как есть - тоже ок

2021-10-11 14:45 UTC, irinanic88 commented on 07-lection5/04-input/index.html
> +            <input type="text" class="text-input__container" disabled
да, это чтобы отобразить. Удаляю

2021-10-11 14:45 UTC, irinanic88 commented on 07-lection5/04-input/input.css
> +.text-input__container {
ок

2021-10-11 15:00 UTC, irinanic88 commented on 07-lection5/04-input/input.css
> +.text-input__container_success ~ .text-input__success-icon {
Исправила

2021-10-11 16:59 UTC, GSemikozov requested changes

2021-10-11 16:59 UTC, GSemikozov commented on components/tabs/tabs.css
> +    position: absolute;
это еще in-progress?)

2021-10-11 17:44 UTC, irinanic88 commented on components/tabs/tabs.css
> +    position: absolute;
ой, извиняюсь. это я закоммитила файл, предназначенный для другой ветки.

2021-10-12 16:00 UTC, GSemikozov approved these changes

2021-10-12 16:00 UTC, merged