Added main page markup
js-tasks-ru/htmlcss-20210916_irina-nic-yu pull request #3
Opened 2021-09-22 13:38 UTC by irinanic88

2021-09-22 13:38 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-22 13:44 UTC, GSemikozov requested changes

2021-09-22 13:44 UTC, GSemikozov commented on package.json
> +    "normalize.css": "^8.0.1",
normalize кроме добавления в качеcтве зависимости еще и надо подключить - либо в index.html либо в main.css :)

2021-09-22 13:44 UTC, GSemikozov commented on components/header/header.css
> +    margin-left: 160px;
вместо такого отступа нужно создать элемент по типу контейнера, который будет выравниваться по середине и иметь max-width для ограничения ширины (по дизайну это видно), и уже в контейнер положить тайтл

2021-09-22 13:44 UTC, GSemikozov commented on components/footer/footer.css
> +    width: 640px;
сам футер это скорее блок на всю ширину страницы с белым фоном, а внутри - контент будет выравниваться внутренним контейнером (про контейнер - ниже)

2021-09-22 13:44 UTC, GSemikozov commented on components/footer/footer.css
> +    font-weight: 500;
по дизайну у тайтла есть отступ снизу от текста + кроме font-size также важно указывать font-family, если он отличается от того, который определен глобально

2021-09-22 15:03 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-22 15:38 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-22 15:41 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-23 16:40 UTC, GSemikozov requested changes

2021-09-23 16:40 UTC, GSemikozov commented on assets/css/main.css
> +@import '~normalize.css';
должен подключаться до любых авторских стилей :)

2021-09-23 16:40 UTC, GSemikozov commented on components/footer/footer.css
> +.footer__description-text {
тут и ниже по классам вышел некий расколбас) 
есть блок, а есть его элементы, соответственно когда описываем один блок - не может здесь же описывать другие блоки. Другими словами структура классов должна выглядеть так:
.footer
.footer__container
.footer__container_small
.footer__description
.footer__title

2021-09-23 16:40 UTC, GSemikozov commented on components/header/header.css
> +.header-container {
тут - надо обратить на комментарий выше ;)

2021-09-27 14:26 UTC, irinanic88 commented on components/footer/footer.css
> +.footer__description-text {
Я не очень поняла этот комментарий. В нашем случае, в футере только два элемента. Мы их расположение центрируем дополнительным миксом footer__что-то ? Я немного запуталась, микс - это класс, который мы добавляем основному блоку, чтобы расставить в нем элементы по местам, так? Или просто всегда делать доп. контейнер и в нем уже - всю эту магию.

2021-09-27 14:26 UTC, irinanic88 commented on assets/css/main.css
> +@import '~normalize.css';
поменяла

2021-09-27 14:26 UTC, irinanic88 commented on components/header/header.css
> +.header-container {
Ок

2021-09-27 14:28 UTC, irinanic88 commented on components/header/header.css
> +.header-container {
А page мы вообще не трогаем, получается?

2021-09-28 19:45 UTC, GSemikozov commented on components/header/header.css
> +.header-container {
может трогать) но конкретно здесь - речь именно о компоненте .header

2021-09-29 19:52 UTC, GSemikozov commented on components/footer/footer.css
> +.footer__description-text {
мы тут разобрались?)

2021-09-29 19:54 UTC, GSemikozov approved these changes

2021-09-29 19:54 UTC, merged